#include "minetypes.h"
#ifndef MENUCONSTANTS_H_INCLUDED
#define MENUCONSTANTS_H_INCLUDED

extern Point SIZESP, PRESETSP, SETSP, SETCELLSBSP, SETCELLSSP, WIDTHBSP, HEIGHTBSP, MINESBSP, WIDTHSP, HEIGHTSP, MINESSP, OWLSP, XSP, XMINE;
extern Size SIZESIZE, PRESETSIZE, SETSIZE, SETCELLSBSIZE, SETCELLSSIZE, DIGITBDIM;

enum
{
    TICKS_BEFORE_START = 5, //pcs
    REPEAT_RATE = 50        //ms
};

#endif // MENUCONSTANTS_H_INCLUDED
